name: fastai
channels:
  - pytorch
  - conda-forge
  - fastchan
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch==1.12.1
  - torchvision==0.13.1
  # - torchaudio==0.12.1
  - cudatoolkit=11.6
  - fastai=2.7
  - pip:
      - ipykernel
      - ipywidgets
      - timm==0.6.12
